### ISSUE TITLE
NameError: name 'get_ot_given_a' is not defined

### ISSUE THREAD

**Issue by Linchenbaobao** [wps712/BitSplit#1]
python main_quant_resnet18_twostep.py -a resnet18_quan --pretrained /data1/pytorch_state_dict/Imagenet/resnet18-5c106cde.pth --act-bit-width 8 --weight-bit-width 4
torch.Size([64, 3, 7, 7])
torch.Size([12000, 3, 7, 7])
torch.Size([12000, 64])
0
Traceback (most recent call last):
  File "main_quant_resnet18_twostep.py", line 691, in <module>
    main()
  File "main_quant_resnet18_twostep.py", line 190, in main
    conduct_ofwa(train_loader, model_pretrained, model_quan, conv, conv_quan, None, 8, prefix=args.prefix+'/conv1', ec=False)
  File "main_quant_resnet18_twostep.py", line 453, in conduct_ofwa
    B_sav, B, alpha = ofwa(W.cpu().numpy(), bitwidth)
  File "/data1/BitSplit-master/quant.py", line 56, in ofwa
    B = get_ot_given_a(W_res*(2**bit), alpha)
NameError: name 'get_ot_given_a' is not defined
I executed the train command, it returned this error.

**Comment by peiswang** [comment]
Error fixed, thanks.
